version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python:3.12  # adjust Python version as needed
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate

      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

workflows:
  version: 2
  build_and_install:
    jobs:
      - build
