version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.12  # adjust Python version as needed
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate

      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

workflows:
  version: 2
  build_and_install:
    jobs:
      - build
