version: 2.1


jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable  # lightweight image with Docker CLI
    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker  # Required for Docker builds on CircleCI

      - run:
          name: Log in to Docker Hub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/myapp:latest .

      - run:
          name: Push image to Docker Hub
          command: docker push $DOCKERHUB_USERNAME/myapp:latest


      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate

      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

workflows:
  version: 2
  build_and_install:
    jobs:
      - build
